### ISSUE TITLE
JSON Scanner exception for Thai Language characters.

### ISSUE THREAD

**Issue by ssarap** [pljson/pljson#190] opened 2020-02-26 12:22 UTC
Off late we have upgraded to pljson_parser api to convert json to XML. We noticed exceptions when the json data contains Thai language characters. But the same content works fine with json_parser API.

Non working case:
`SELECT pljson_xml.json_to_xml(pljson(to_clob('{"PERSON_ID":{"value":267},"ASSIGNMENT_ID":{"value":259},"GOAL":{"value":"ข้มู"},"postType":"userSubmitted","submittedFieldId":"ADD"}'))) FROM dual;`

Working case:
`SELECT json_xml.json_to_xml(json(to_clob('{"PERSON_ID":{"value":267},"ASSIGNMENT_ID":{"value":259},"GOAL":{"value":"ข้มู"},"postType":"userSubmitted","submittedFieldId":"ADD"}'))) FROM dual;`

**Note:** We are using Oracle 11g.

Any resolution will greatly help us.
Thanks !

**Comment by jsumners** [comment] 2020-02-26 12:44
Is the string UTF-8?

**Comment by dsnz** [comment] 2020-02-26 15:21
Hi,

Your Thai text   ``` ข้ม ``` is two characters visually but 3 characters really (each 3 bytes), the first two are a character and an associated sign mark on top of the first character, or better `` an accent character `` to be combined with the preceding character.

Internally we use ```lengthc()``` which returns 2 complete characters (combined).
However ```substr()``` works with incomplete characters and returns in succession each individual character causing problem with parsing.

It seems to be a bug and it's a case I had not thought (I used lengthc() instead of length() in order to emphasize and make it visible that we work with characters and not bytes).
The inconsistent handling of unicode in VARCHAR2 and CLOB is the cause of workarounds and tricks within the code so that we support all cases with unicode input and eventually such bugs arise.

Let me change the logic to ```length()``` internally and hope there is no other issue (especially with clob input) and so we fix this bug too.

Within the next 2 days a fix will be posted. Please try it and report back.

**Comment by ssarap** [comment] 2020-02-27 07:33
@dsnz Thank you so much for quick turn around. 
We have faced another exception ORA-20100: JSON Scanner exception @ line: 1 column: 2 - Unexpected char: & for Thai characters. Tried to decode using dbms_xmlgen.entity_decode but it dint work and the same text was working in json_parser.
I will provide more details on this case shortly.

**Comment by dsnz** [comment] 2020-02-27 07:35
please give a short example that demonstrates the error

**Comment by ssarap** [comment] 2020-02-27 11:34
Please find the test case here:

Non working:
`SELECT pljson_xml.json_to_xml(pljson(to_clob('{"translation":"แสดงมากขึ้น","input":{"source":"en","target":"de","text":"show more"}}'))) FROM dual;`

Working:
`SELECT json_xml.json_to_xml(json(to_clob('{"translation":"แสดงมากขึ้น","input":{"source":"en","target":"de","text":"show more"}}'))) FROM dual;`

**Comment by dsnz** [comment] 2020-02-27 11:42
Both work for me as it should. Using json_xml or pljson_xml should be same (json_xml is synonym for pljson_xml). Check that you have downloaded and made clean install of latest version.

**Comment by ssarap** [comment] 2020-02-27 11:46
This works fine in our instance where Thai language is not installed but it fails in other instances where Thai language is installed.

**Comment by dsnz** [comment] 2020-02-27 11:48
Please be more specific. Give the database and session character sets (both) for your instances.

**Comment by ssarap** [comment] 2020-02-27 12:35
Both have NLS_CHARACTERSET	= AL32UTF8

**Comment by dsnz** [comment] 2020-02-27 13:01
The instance databases are identical. Since you say the other instances have the Thai language installed, you probably mean that the OS uses the Thai language and so, the session NLS language parameters are probably different. For a complete info about nls parameters run the following (both sql statements) in a working and non-working instance (as the user running the example you sent) and post the results.

```
SET PAGES 999
SET LINES 300
COL PARAMETER FOR A30
COL DATABASE FOR A30
COL INSTANCE FOR A30
COL SESSION FOR A30
SELECT DB.PARAMETER, DB.VALUE "DATABASE", I.VALUE "INSTANCE", S.VALUE "SESSION"
FROM   NLS_DATABASE_PARAMETERS DB, NLS_INSTANCE_PARAMETERS I, NLS_SESSION_PARAMETERS S
WHERE  DB.PARAMETER=I.PARAMETER(+) AND DB.PARAMETER=S.PARAMETER(+)
ORDER BY 1;
```
```
select *
from v$nls_parameters;
```

**Comment by ssarap** [comment] 2020-02-28 06:55
Here are the results from both instances.
[non working instance.txt](https://github.com/pljson/pljson/files/4265626/non.working.instance.txt)
[working instance.txt](https://github.com/pljson/pljson/files/4265627/working.instance.txt)

**Comment by dsnz** [comment] 2020-02-28 12:47
I tend to think that it's an issue with Oracle 12 and unfortunately I don't have a working Oracle 12 to check myself. But let's gather some more info to understand better what's going on.

1. In which tool do you try the sql statements ? (both the json_to_xml statements and the nls statements I asked you to run)
at least can you confirm it's the same tool for all sql statements ?

2. run the following in your tool and in both instances and post the results

```
select length('ขึ้')
from dual;

select dbms_lob.getlength(to_clob('ขึ้'))
from dual;

select substr('ขึ้', 1, 1)
from dual;

select substr('ขึ้', 2, 1)
from dual;

select substr('ขึ้', 3, 1)
from dual;

select substr('ขึ้', 4, 1)
from dual;
```

**Comment by ssarap** [comment] 2020-03-02 09:36
We are using Sql developer for running queries.
Here are the results from working and non-working instances.
[queries_non_working_instance.txt](https://github.com/pljson/pljson/files/4274567/queries_non_working_instance.txt)
[queries_working_instance.txt](https://github.com/pljson/pljson/files/4274568/queries_working_instance.txt)

**Comment by dsnz** [comment] 2020-03-03 13:09
The only way I see now especially since you use SQL Developer too is to give me VPN access to the non-working instance. I need just the VPN connection details (preferably OpenVpn) and the tns connection settings for a new Oracle schema where you will have installed the latest version. Contact me by email to arrange this.

**Comment by ssarap** [comment] 2020-03-16 07:49
I dont think we can share our VPN details. 
If possible can we connect through video conference and debug the issue?

**Comment by dsnz** [comment] 2020-03-16 12:57
Hi

you will really share only your external ip which is not so private and secret information, all the other data (typically just a password) can be a temporary new profile (including a single internal routing to your db server only) which can be dropped later

I proposed the vpn connection to help you debug this strange issue because all tests I gave you to try returned correct results and so I tend to believe it's something more related to session settings than code or database settings and unfortunately I don't see other method to debug
all sites enable at times a vpn connection for outside support

a video conference is so impractical that it's impossible
it's impractical due to time difference (estimate 5 hours at least), my fragmented availability and my usually debugging on-off at multiple irregular times and of course the associated difficulty of finding common times with you, the long time to communicate back and forth and synchronize information in video conference, the language and settings of your tools and many others ... including the current covid-2019 effect (2 kids doing remote lessons !)

I hope you reconsider the vpn thing and understand it does not compromise your safety while leading at a quick resolution of this strange issue (and also allow to release the latest pljson version)

**Comment by ssarap** [comment] 2020-04-17 10:36
I will try to speak to our DBA and reach out to you.

**Comment by dsnz** [comment] 2020-04-17 11:08
since the response has been late I will proceed in the next month with an update and a new release  that had been long planned and then will fix your issue (if there is an issue in the end)
anyway your dba should reach me

**Comment by dsnz** [comment] 2020-04-18 17:27
I will close this now as there is no confirmed issue yet.
If there is any development (after testing at your server) I will open it again and update.

P.S. Have you ever tried version 3 ? Then check that you have not mixed version 2 and version 3 installation ... Read the version 3 README (branch: develop_v3) for updated installation instructions.
The installation scripts are now version specific (this means if you installed 2 then you must run the version 2 uninstall script before installing 3, and you must uninstall 3 with version 3 uninstall script before installing version 2) while previously there was an overlap which might affect 2 versions to be installed at the same time on the same instance (of course in different schemas).

**Closed by dsnz** 2020-04-18 17:27 UTC
Labels: bug
