### ISSUE TITLE
ORA-04030: out of process memory - after version upgrade

### ISSUE THREAD

**Issue by phppinheiro** [pljson/pljson#165] opened 2019-02-08 15:21 UTC
Hi,

After upgrade from version 1.0.4 to 2.4.0 the same code results in a ORA-04030: out of process memory (4 GB)

Full error description:
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pmucpcon: tds)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pmuosdest:#0)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pmuccst: adt/record)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,pl/sql vc2)

Attached a test case to replicate the error.

[ora-04030_testcase.txt](https://github.com/pljson/pljson/files/2845650/ora-04030_testcase.txt)

Best regards

**Comment by phppinheiro** [comment] 2019-02-08 15:24
Sorry, test case update.

[ora-04030_testcase.txt](https://github.com/pljson/pljson/files/2845664/ora-04030_testcase.txt)

**Comment by phppinheiro** [comment] 2019-02-08 15:27
Oracle Version 11.2.0.4

**Comment by dsnz** [comment] 2019-02-08 16:43
Hi,

It is very unlikely that this error has been caused by PLJSON, rather your system is up for long time or something else fragmented your memory and you happen to see this error when running PLJSON.
I suggest that you check your alert file for the first appearance of this error.

I can't run your testcase because it is not correct and self contained !
I had to fix a few things like the type ```TABLE_VARCHAR``` which was out of order and bad commenting which corrupted the ```EXECUTE IMMEDIATE``` string, but still I miss the table ```table_number``` with some rows.

Please provide a testcase file that we can run without editing and can show immediately the problem.

**Comment by phppinheiro** [comment] 2019-02-08 16:57
Hi,

Test case attached with table_number type and table_varchar in the correct order.

The error also happends after a database restart. 

[ora-04030_testcase.txt](https://github.com/pljson/pljson/files/2846014/ora-04030_testcase.txt)

**Comment by phppinheiro** [comment] 2019-02-08 16:58
Sorry, with execute immediate correction

[ora-04030_testcase.txt](https://github.com/pljson/pljson/files/2846033/ora-04030_testcase.txt)

**Comment by phppinheiro** [comment] 2019-02-08 17:03
One additional note: if I limit the number of record to 28 (FROM table_temp where rownum <= 28) it takes near 30 seconds, if I change to 29 records ORA-04030 is raised.

**Comment by dsnz** [comment] 2019-02-11 08:47
Hi,

I have verified the behavior you described and I have analyzed it a lot.

It must be an Oracle bug when working with collections of objects. I think it is a variation of "Bug 8323894 - Repeatedly extending and deleting a collection of PLSQL objects leaks PGA memory (Doc ID 8323894.8)" which is supposedly corrected but a lot of Oracle bugs reappear or manifest in subtle variations (this bug has not exactly the same behavior as 8323894 but very similar). I have prepared a short script that demonstrates this bug and will soon submit it to Oracle. When there is an update from Oracle I will update this issue. If there is a workaround we will know rather soon (within a week), but I will be able to provide a pljson fix using it in about 3 weeks(!)  as the next week I will be very busy and impossible to work on pljson. If there is no workaround then Oracle bug fixing will probably last long, maybe a year ... (an existing bug that troubles performance of the pljson parser has not been fixed for over a year now).

I strongly suggest that you install pljson v3.0 which does not suffer from this bug and works very fast and without any problem for the example you posted (all 64 records in less than 2 seconds). You will find it in the 'develop' branch (in fact there is a note when entering the 'main' branch that encourages you to upgrade). Any new features (and I'm planning a few in the next months) will be implemented only on v3.0. The current v2.0 is kept for compatibility reasons and will be maintained only for bugs and perhaps minor enhancements. If you have any questions about v3.0 feel free to open a new issue.

In the meantime and for completeness of my investigation I would like you to send me a zip of the 1.0.4 pljson code you say it worked correctly (I can't understand what code you mean because all old pljson code versions before 2.0 had the same version 1.0.4).

**Comment by phppinheiro** [comment] 2019-02-11 09:07
Hi,

Thanks for the feedback. I'll install version 3.0 and test again.

Attached version 1.0.4 (only difference is a rename from pljson to json).


[json_v1.0.4.zip](https://github.com/pljson/pljson/files/2850346/json_v1.0.4.zip)

**Comment by dsnz** [comment] 2019-03-01 13:46
hi, on which OS are you ?
are you okay with 3.0 ?

**Comment by phppinheiro** [comment] 2019-03-01 14:11
Hi, OS is Linux (in this case CentOS release 6.5).
Yes, v3.0 is OK.

**Comment by dsnz** [comment] 2019-03-01 14:20
Good that are you are fine with 3.0.

I'm discussing the matter with Oracle over an SR. Of course, as I am not representing a big business entity things move slow (the SR was assigned to an analyst who went on vacation ..! and bug resolution even slower ..). It may be necessary that I ask you to carry the same experiment using v2.0 again (you should do in a separate test schema) using also some proposed workarounds. I will do my best to avoid this and try all workarounds on my Windows but there is a small probability that they may insist to try them on Linux too.

**Comment by phppinheiro** [comment] 2019-03-01 14:25
Ok, no problem. I can test workarounds if you need.

**Comment by dsnz** [comment] 2019-03-18 17:38
Some good news,

It has been verified by Oracle that there is a bug, specifically **bug 29499245**.
I expect some information on possible workaround and bug fix timeline and will post here.
Since I represent a small installation I don't think it will be fixed soon (another bug that was found thanks to the PLJSON project is already 1 year old ...). If any PLJSON user represents a big Oracle installation then let's ask for resolving this bug, usually Oracle respond quickly for big customers.

**Comment by dsnz** [comment] 2019-08-02 07:11
last update from Oracle Support on this issue; I paste verbatim the main points

"I got update from the development team that they are piled up under series of highly escalated issues and this bug is going to take some time to get picked up."

"Moving NRD (Next Response Date) to mid of Sep 2019 for now."

**Comment by mar1va** [comment] 2019-12-15 21:17
Hello, 

(I have same error)

I have a json file (500 MB) imported into database, and need instructions how to parse large json file.

Thank you.



Note: I have installed latest version of PLJSON.

Simple code attached.
[gitHub_my_example.txt](https://github.com/pljson/pljson/files/3965461/gitHub_my_example.txt)


Oracle db: Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
OS: Windows Server 2008, 4GB


Error:
ORA-04030: out of process memory when trying to allocate 16328 bytes (koh-kghu call ,kollrsz)
04030. 00000 -  "out of process memory when trying to allocate %s bytes (%s,%s)"
*Cause:    Operating system process private memory was exhausted.

**Comment by dsnz** [comment] 2019-12-15 21:46
Hi,

Unfortunately Oracle Development has not done anything for more than a year for this bug (and we have another serious bug pending for fix for longer time).
First I would like to suggest that you check that you hit this bug. Your code processes many json pieces (which it reads from a table). If all these json pieces have the same structure and you hit the bug then your application would crash from the first piece already. The piece need not be huge, even less than 200 bytes is enough.
So, output more information on what is going on (a message when each piece is processed and its size) and try to understand if you are affected by this bug.

If you are affected then install the version 3.0 pljson which you can find in the develop_v3 branch.
If not then you need increase available memory for processes.

**Comment by mar1va** [comment] 2019-12-15 22:00
Hello,

Thanks for quick reply. I have downloaded latest version of the pljson, and I receive this error when clob_data (column in table) needs to be "assign" to json_list.

"v_json_list:=json_list(v_clob);"

The script is running about 900 s and error is rise.

This is first time I use pljson to parse large file, so I don’t know if I'm doing this on right way.

Please advise.

Thank you.

**Comment by dsnz** [comment] 2019-12-15 22:15
Well, if you installed v3.0 then you have just a memory error.
I suggest that you start with a smaller json text and then continue with larger ones (for example start at 10 MB, then 50 MB, then 100 MB, then 200 MB) and at the same time using operating system commands measure the memory consumption and get a calculated estimation of how much extra memory a 500 MB json text will need and then try to make available that much memory.
(remember, the memory that can be used is what is left after the SGA, PGA, usual process memeory, other application memory in your system and memory for the 500 MB json clob which is really 1 GB as clob data is stored in 2-byte Unicode format).
I am afraid we can't provide more detailed help with this as it is not really a pljson issue and a lot depends on your installation specifics (for example you may hit on a 2G/4G process limit in some operating system setups).

**Closed** 2022-10-09 19:27 UTC
Labels: waiting Oracle-bugfix
