### ISSUE TITLE
Getting json parser error when trying to read?

### ISSUE THREAD

**Issue by kinju4374** [pljson/pljson#169] opened 2019-07-18 17:06 UTC
Hi, I am getting json parser error when I am trying to access a string paramter with emojis using json_ext.getstring(json, parameter_name). Can someone suggest a workaround to access this parameter with emoji using pljson API? It is affecting my live web services.

**Comment by dsnz** [comment] 2019-07-18 17:23
You must post the shortest example code that demonstrates your problem, so that others can see and understand it.

**Comment by kinju4374** [comment] 2019-07-19 05:19
Hi @dsnz ,

Here is the example of the json. It works in Notepad++ also when I try to parse using JsonViewer plugin, I don't get any error but I am getting an error using PL/SQL

`{
	"P_LANGUAGE_CODE": "EN",
	"P_UDID": "12345",
	"P_DEVICE_NAME": "Kinjan 💘",
	"P_CLIENT_ID": 1,
	"P_DEVICE_DETAIL": {
		"DEVICE": "iPhone",
		"SYSTEM_VERSION": "12.3.1",
		"ZIP_VERSION": 707,
		"SYSTEM_NAME": "iOS",
		"MODEL": "iPhone8,1",
		"BRAND": "Apple",
		"APP_VERSION": "6",
		"LANG_CODE": "EN",
		"TEST_MODE": 0,
		"IP_ADDR": "192.168.0.3"
	},
	"P_APP_VERSION": 6,
	"P_WS_NAME": "iTestWebservice",
	"P_ZIP_VERSION": 707
}`

And I am trying to read this json using the following code

`V_RESULT_JSON := JSON(V_JSON_CLOB);`

I am getting the above json input in V_JSON_CLOB, when I print V_JSON_CLOB, it shows me proper json but when I try to cast JSON using `JSON(V_JSON_CLOB)`, it gives me the error.

Can you suggest, what I would be doing wrong?

**Comment by dsnz** [comment] 2019-07-19 15:48
Hi,

I have seen the error and I am checking it. I will reply by tomorrow because I want to see carefully what's happening and not do hasty things.
Can you please tell me the unicode code of the stricken heart ?

**Comment by kinju4374** [comment] 2019-07-19 15:50
Hi,

I am not sure about the unicode to be honest but you can try any emojis and it will give you same error.

**Comment by dsnz** [comment] 2019-07-19 15:57
Nope, for ♡ for example works. But i found it and is a recent unicode entry. I'm afraid it's an Oracle issue but as I said I want to check carefully and will reply tomorrow or the next days.

**Comment by kinju4374** [comment] 2019-07-19 16:20
Ok thanks.

If possible, if you have any suggestions which I can try then please let me know to overcome this error.

**Comment by dsnz** [comment] 2019-07-19 16:32
Hi,
It is a clob issue. I want to check if it is a feature (!) or a bug. From what I remember it must be a feature.
To understand what happens run the following code

```
DECLARE
utext_char varchar2(32767) := '💘';
utext_clob clob := '💘';
BEGIN
  dbms_output.put_line(length(utext_char));
  dbms_output.put_line(length(utext_clob));
END;
``

you get output
```
1
2
```

The emoji you gave needs 4 UTF-8 bytes or 2 UTF-16 characters.
If I remember well, clobs use a utf-16 representation
and count a single utf-16 sequence as a character.
In your case the clob thinks there are 2 characters, not 1 !

The parsing problem eventually is because we get wrong information about total length
and while the whole json is parsed well within our plsql code, in the end an error is produced
because it appears that not all of json text has been consumed.

I will check all these carefully and see if we can have a workaround in code.
In case of a possible code workaround the solution will be ready in about one week as
I will travel abroad these days and will work on this at opportune times.
Currently I suggest that you use varchar2 if possible.

**Comment by kinju4374** [comment] 2019-07-19 17:04
Thanks @dsnz. As it may large json, we have used clob but no problem, I will wait for some days for the workaround and will try myself if I find something relevant to solve this issue.

**Comment by dsnz** [comment] 2019-07-19 17:25
The good news is that a workaround is possible I think,
but I have to check all code affected and also test for some border cases (that is the workaround will work for the example you gave but may not work with an example of a different size).

For a quickie you can change in prepareClob the

```
    temp.len := dbms_lob.getlength(buf);
```

with

```
    temp.len := lengthc(buf); --dbms_lob.getlength(buf);
```

and you will have no parse error.
Tell me if any other error appears in your application as it will be helpful while I prepare the final workaround.

**Comment by kinju4374** [comment] 2019-07-20 02:25
Yes @dsnz. I have few more emojis for which I was getting same error, will share with you soon.

Thanks

**Comment by kinju4374** [comment] 2019-07-20 03:37
Hi @dsnz ,

Few more examples where I am getting json parser error due to emoji's

`test1🌺`
`test2🧡`
`💖💜test3💜💖`
`💖test4💖`
`test5📱`
`test6😉`
`test7😊`

Thanks

**Comment by dsnz** [comment] 2019-07-28 18:08
update
as I was very busy the last week, fix will be ready by the end of this week (Aug 2) definitely

**Comment by dsnz** [comment] 2019-08-01 20:32
@kinju4374  are you using the master branch (v 2.0) or the development branch (v 3.0) ?

**Comment by kinju4374** [comment] 2019-08-02 05:21
Hi @dsnz , I am not sure as it was added by one of my employees. I think it should be v2.0, but is it a way to check in any package where you might have mentioned it?

**Comment by kinju4374** [comment] 2019-08-02 05:35
@dsnz Also, if we convert it to Unicode, then will it not create an issue with integrations?

**Comment by dsnz** [comment] 2019-08-02 07:05
if in your database there is a type PLJSON_STRING or PLJSON_NUMBER then it's v3.0 else it's v2.0
(there is a pljson_parser.get_version() function but returns a usable result only if you downloaded a release from github and not if you downloaded a full branch) 

I don't understand what you mean by "if we convert it to Unicode, then will it not create an issue with integrations?" ?
do you mean if the fix will not create any other issue ?
well I will try that the fix will be the best possible, but of course there are hidden bugs always :)
the whole programming in Oracle for 4 byte unicode chars in clobs is "schizophrenic" I would say (and I have to repeat that this bug as quite many others fixed in the past are not real PLJSON bugs but side effects of Oracle bugs ! and indeed the way these characters are handled in dbms_lob package is buggy)
also I will fix only the parsing, there will be some possible issues with a few other pljson functionalities that I will mention anyway in a next post but I can't fix now (but of course will try to fix if you fall into them and report as a new issue)
in any case you will have code that performs better than now

**Comment by kinju4374** [comment] 2019-08-02 07:20
Hi @dsnz ,

I tried to check using your function and its showing **PL/JSON 2.4.0**

**Comment by dsnz** [comment] 2019-08-02 12:38
thank you,
is it also possible that you can provide an example json more than 32 kb to parse ?
(with a few emojis, but not full with emojis, just a realistic json from your application perhaps modified by hand to not contain sensitive information)

**Comment by dsnz** [comment] 2019-08-05 14:27
@kinju4374  we expect a sample json from you for final test before committing the fix
let's finish with this issue quickly :)

**Comment by kinju4374** [comment] 2019-08-06 06:04
@dsnz I don't have a json with 32 kb to parse but I have a sample json with around 2600 characters not sure which will be helpful to you or not.

`{
	"P_LANGUAGE_CODE": "EN",
	"P_DEVICE_DETAIL": {
		"LATITUDE": "50.815983",
		"IP_ADDR": "192.168.0.8",
		"DEVICE": "iPhone",
		"USER_AGENT": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
		"MODEL": "iPhone7,2",
		"ZIP_VERSION": 144,
		"LONGITUDE": "-1.062227",
		"SYSTEM_NAME": "iOS",
		"APP_VERSION": "6",
		"SYSTEM_VERSION": "12.3.1",
		"LANG_CODE": "EN",
		"TEST_MODE": 0,
		"BRAND": "Apple"
	},
	"P_CLIENT_ID": 1,
	"P_APP_VERSION": 6,
	"P_USER_ID": 1234,
	"P_COUNCIL_ID": 20,
	"P_FORM_ID": 1345,
	"P_WS_NAME": "iTestWS",
	"P_TEST_DATA": {
		"TEST_DATA": [
			{
				"PARAM_1": {
					"ID": "63756",
					"VALUE": "Test"
				},
				"PARAM_2": {
					"ID": "67098",
					"VALUE": "Please tell us the problem"
				}
			},
			{
				"PARAM_1": {
					"ID": "",
					"VALUE": "test@gmail.com"
				},
				"PARAM_2": {
					"ID": "66973",
					"VALUE": "Please provide your email address so we can contact you should we require further information"
				}
			},
			{
				"PARAM_1": {
					"ID": "",
					"VALUE": {
						"LOCATION_DATA": {
							"INCIDENT_LONGITUDE": "-1.0662227",
							"LOCATION": "1 Test Rd, Test PO3 5AS, UK",
							"INCIDENT_LATITUDE": "50.8915983",
							"REPORT_ADDRESS2": "Test Road",
							"REPORT_COUNTRY": "United Kingdom",
							"GEO_LOCATION_TYPE": "ROOFTOP",
							"REPORT_ADDRESS1": "1",
							"GEO_TYPES": "street_address",
							"REPORT_ADDRESS_NUMBER": "1",
							"REPORT_STATE": "England",
							"IS_REVERSEGEOCODE_DONE": 1,
							"REPORT_PINCODE": "PO3 5AS"
						}
					}
				},
				"PARAM_2": {
					"ID": "67081",
					"VALUE": "Tap here to select the location from the map"
				}
			},
			{
				"PARAM_1": {
					"ID": "",
					"VALUE": "As explained previously manipulating the parking with this moped. Not acceptable. "
				},
				"PARAM_2": {
					"ID": "67433",
					"VALUE": "Please provide details"
				}
			},
			{
				"PARAM_1": {
					"ID": "",
					"VALUE": "976115:976116"
				},
				"PARAM_2": {
					"ID": "67302"
				}
			},
			{
				"PARAM_1": {
					"ID": "",
					"VALUE": "A gentleman who lives on the corner of Highgate Road uses this moped to manipulate the parking. If his wife goes out he moves the moped into the space, they have two cars a van and a moped. Not community spirited AT ALL 🤬🤬"
				},
				"PARAM_2": {
					"ID": "71676",
					"VALUE": "Please provide any additional information about where the problem is to help us find it"
				}
			}
		]
	},
	"P_ACCESS_KEY": "ABCD1234567890",
	"P_CATEGORY_ID": 4374
}`

**Comment by dsnz** [comment] 2019-08-06 21:05
Please, reinstall branch **master** (download zip of branch; I cannot make a new release now as I will be making some more commits next week and then there will be a new release),
test extensively with your application and give feedback if the issue is solved.
In case a new error appears (unrelated to parsing), then mention briefly here and open a new issue for it.

**Comment by kinju4374** [comment] 2019-08-08 09:05
Thanks, @dsnz.

I will check in my development server and let you know the results.

**Comment by kinju4374** [comment] 2019-08-09 10:13
@dsnz Can you suggest in which SQL files, you have done changes to support emoji's, so I can check the same package in my development and do the necessary changes based on comparison and be 100% sure

Thanks

**Comment by dsnz** [comment] 2019-08-09 10:18
@kinju4374 
you should download and reinstall, doing manual changes is difficult to do correctly and error prone

all the changes are in https://github.com/pljson/pljson/pull/172/files
from where you can gather the sql files that are changed

**Comment by kinju4374** [comment] 2019-08-09 10:25
Thanks @dsnz , from the reference link, only pl_json parser has been changed and one of the file in testsuite. Thanks

**Comment by dsnz** [comment] 2019-08-19 18:54
@kinju4374 
if you don't give feedback, I must consider this as solved as I need to push some commits to synchronize both versions of pljson

**Comment by kinju4374** [comment] 2019-08-21 07:09
@dsnz Yes, it has resolved the issue. Thanks for fixing it.

**Closed** 2019-08-21 22:01 UTC
Labels: bug
