### ISSUE TITLE
"ORA-30625: method dispatch on null self argument is disallowed" when using get_json_value

### ISSUE THREAD

**Issue by Hawk03** [pljson/pljson#8] opened 2015-03-13 09:31 UTC
I'm using your package to parse json content and insert it into oracle table. One column is coming through as base64 (jpeg format), so I'm using the following line to extract the content:

l_val := json_ext.get_json_value(json(l_list.get(i)),'Photo');

However, whenever the value is null, it is returning the error: 

ORA-30625: method dispatch on null self argument is disallowed

This does not happen for other columns when null (not base64) where I use something like this to extract the content:

A_Name       := json_ext.get_string(json(l_list.get(i)),'Name');

Is this misuse of get_json_value?

**Comment by jsumners** [comment] 2015-03-13 12:28
I have no idea what your data structure looks like, but it seems to me you are performing the access in a very complicated way. Just the `.get` method on your JSON object.

Also, this looks an awful lot like misusage and not a bug. Therefore I am closing it. If you can provide more details that show it to be an actual bug, then reopen the case.

**Closed by jsumners** 2015-03-13 12:28 UTC
