### ISSUE TITLE
efficiency

### ISSUE THREAD

**Issue by sqlplus** [pljson/pljson#114] opened 2018-02-07 07:21 UTC
When I use PLJSON to deal the CLOB type，it running slowly。How  to  solve this problem? If you have solusion,Please tell me！ Thank you

**Comment by jsumners** [comment] 2018-02-07 14:01
You are not providing any detail to determine what your issue is, but I suspect it is a duplicate of #61.

**Closed** 2018-04-23 16:05 UTC
