### ISSUE TITLE
convert xml to json

### ISSUE THREAD

**Issue by dda-jihua-zhong** [pljson/pljson#18] opened 2015-12-09 22:14 UTC
I have following xml

```xml
<?xml version="1.0"?>
<report>
	<summary>
		<nbr>200900013152</nbr>
		<ver>1</ver>
		<report-type>Permit</report-type>
		<sub-proj-count>0</sub-proj-count>
		<publish-date>20090305</publish-date>
		<first-publish-date>20090305</first-publish-date>
	</summary>
	<data>
		<proj-title>
			<title-code>
				<title ci = "N">2 Houses</title>
			</title-code>
		</proj-title>
		<p-location>
			<project-location>
				<title-code>
					<p-adline>
						<p-adline1 ci = "N">5643 Wild Horse Dr</p-adline1>
						<p-adline2 ci = "N">Dollar Run Ln</p-adline2>
					</p-adline>
					<p-county-name ci = "N">MARION</p-county-name>
					<p-fips-county>IN097</p-fips-county>
					<p-city-name ci = "N">Indianapolis</p-city-name>
					<p-state-id ci = "N">IN</p-state-id>
					<p-country-id ci = "N">USA</p-country-id>
				</title-code>
			</project-location>
		</p-location>
		<status>
			<project-status>
				<title-code>
					<status-text>(BPEO21)</status-text>
				</title-code>
			</project-status>
		</status>
		<project-valuation>
			<title-code>
				<currency-type>USD</currency-type>
				<est-low ci = "N">150000</est-low>
			</title-code>
		</project-valuation>
		<additional-details>
			<title-code>
				<subcontract-method ci = "N">Owner (Private)</subcontract-method>
				<owner-class ci = "N">Private</owner-class>
				<permit-issue-date>20090213</permit-issue-date>
			</title-code>
		</additional-details>
		<project-type>
			<title-code>
				<proj-type pi = "Y" ci = "N">Sale/Spec Homes</proj-type>
			</title-code>
		</project-type>
		<project-stage>
			<title-code>
				<stage-desc pi ="Y" ci ="N">Permit</stage-desc>
			</title-code>
		</project-stage>
		<project-work-type>
			<title-code>
				<work-type ci = "N">New Project</work-type>
			</title-code>
		</project-work-type>
		<details>
			<structural-data>
				<title-code>
					<nbr-of-bldg ci = "N">2</nbr-of-bldg>
				</title-code>
			</structural-data>
			<project-type-specific-info>
				<title-code>
					<flex-label>
						<flex-desc>Total # of Units</flex-desc>
						<flex-value ci = "N">2</flex-value>
					</flex-label>
				</title-code>
			</project-type-specific-info>
		</details>
	</data>
</report>
```

use json_ml and print, convert xml to json we got 

```
["report", 
    ["summary", 
      ["nbr", "200900013152"], 
      ["ver", "1"], 
      ["report-type", "Permit"], 
      ["sub-proj-count", "0"], 
      ["publish-date", "20090305"], 
      ["first-publish-date", "20090305"]
    ], 
    ["data", 
        ["proj-title", ["title-code", ["title", { "ci" : "N"}, "2 Houses"]]], 
        ["p-location", 
             ["project-location", 
                ["title-code", 
                    ["p-adline", ["p-adline1", { "ci" : "N"}, "5643 Wild Horse Dr & 5510"], 
                                 ["p-adline2", {"ci" : "N"}, "Dollar Run Ln"]], 
                    ["p-county-name", {"ci" : "N"}, "MARION"], 
                    ["p-fips-county", "IN097"], 
                    ["p-city-name", {"ci" : "N"}, "Indianapolis"], 
                    ["p-state-id", {"ci" : "N"}, "IN"], 
                    ["p-country-id", {"ci" : "N"}, "USA"]
                ]
              ]
        ], 
        ["status", ["project-status", ["title-code", ["status-text", "(BPEO21)"]]]], 
        ["project-valuation", ["title-code", ["currency-type", "USD"], ["est-low", {"ci" : "N"}, "150000"]]], 
        ["additional-details", ["title-code", ["subcontract-method", {"ci" : "N"}, "Owner (Private)"], ["owner-class", {"ci" : "N"}, "Private"], ["permit-issue-date", "20090213"]]], 
        ["project-type", ["title-code", ["proj-type", {"pi" : "Y","ci" : "N"}, "Sale/Spec Homes"]]], 
        ["project-stage", ["title-code", ["stage-desc", {"pi" : "Y","ci" : "N"}, "Permit"]]], 
        ["project-work-type", ["title-code", ["work-type", {"ci" : "N"}, "New Project"]]], 
        ["details", 
            ["structural-data", ["title-code", ["nbr-of-bldg", {"ci" : "N"}, "2"]]], 
            ["project-type-specific-info", ["title-code", ["flex-label", ["flex-desc", "Total # of Units"], ["flex-value", {"ci" : "N"}, "2"]]]]
        ]
    ]
]
```

you can see that  there are lots of "[" and "]" for json elements which is not right to me. 
How do we convert the [ to { without replacing the real array in json ?

However, use the online xml to json convertion tool http://www.freeformatter.com/xml-to-json-converter.html#ad-output  we can easily get the right format.

**Comment by jsumners** [comment] 2015-12-09 22:50
Technically, it's working as intended. If you look at [the source](https://github.com/pljson/pljson/blob/master/src/addons/jsonml.sql#L58) you will see that it uses an XSLT stylesheet to do the conversion. What you will have to do is supply a different stylesheet that does what you want. The problem is the attributes; if the xml were guaranteed to not have attributes, only values, then a stylesheet like you are expecting would be possible for general use. As it is, this is a compromise for the most generic solution.

 I'm going to close this since it isn't really a bug. But if you have a solution that would work better in a general case, feel free to submit a pull request with your solution.

**Closed by jsumners** 2015-12-09 22:50 UTC
