### ISSUE TITLE
Slow pljson_ext.get_json_value

### ISSUE THREAD

**Issue by pcrex** [pljson/pljson#105] opened 2017-10-25 06:58 UTC
On Oracle DB 11.2.0.1.0 the line `o := pljson(ret);` takes about 3 sec.
JSON file size is only 114 KB.
Is there a way to speed it up?

**Comment by jsumners** [comment] 2017-10-25 12:14
Duplicate of #61.

**Comment by dsnz** [comment] 2017-10-25 12:52
Hi,

As you understand pljson is pure PL/SQL code and so cannot be as fast as other C libraries.
A lot depends also on the structure and content of your json data and less on the size in bytes.

I plan to make an improvement based on object representation instead of sys.anydata but without any change in the current parsing logic. The amount of speed improvement cannot be estimated unfortunately.
I ask you to be patient until next update and also help in benchmarking.

Please send us the json file you use and kindly run the following benchmark and report here

```
declare
  test_sec number;
  
  procedure bench1(test_dir varchar2, test_file varchar2, test_sec out number) is
    test_json pljson;
    test_clob clob;
    test_bfile bfile;
    
    t_start timestamp;
    t_stop  timestamp;
    t_sec NUMBER;
    
    dest_offset number := 1;
    src_offset number := 1;
    bfile_csid number := 873; -- nls_charset_id(''AL32UTF8');
    lang_context number := dbms_lob.default_lang_ctx;
    warning number;
  begin
    dbms_lob.createtemporary(test_clob, TRUE, dbms_lob.SESSION);
    dbms_lob.trim(test_clob, 0);
    
    test_bfile := BFILENAME(test_dir, test_file);
    dbms_lob.open(test_bfile, DBMS_LOB.LOB_READONLY);
    dbms_lob.loadclobfromfile(test_clob, test_bfile, DBMS_LOB.LOBMAXSIZE, dest_offset, src_offset, bfile_csid, lang_context, warning);
    dbms_lob.close(test_bfile);
    
    t_start := SYSTIMESTAMP;
    
    test_json := pljson(test_clob);
    
    t_stop := SYSTIMESTAMP;
    t_sec := extract(second from t_stop - t_start);
    test_sec := t_sec;
    
    dbms_output.put_line(test_file || ' ' || to_char(t_sec) || ' sec ' || dbms_lob.getlength(test_clob) || ' char');
    dbms_lob.freetemporary(test_clob);
  end;
begin
  bench1('DATA_PUMP_DIR', 'canada.json', test_sec);
  bench1('DATA_PUMP_DIR', 'citm_catalog.json', test_sec);
end;
/
```

you must put the following common json benchmark files

```
https://raw.githubusercontent.com/miloyip/nativejson-benchmark/master/data/canada.json
https://raw.githubusercontent.com/miloyip/nativejson-benchmark/master/data/citm_catalog.json
```

 in your DATA_PUMP_DIR (or put in any other place in server and change in benchmark code DATA_PUMP_DIR to the correct database directory that points to that place).

**Comment by dsnz** [comment] 2017-10-25 13:46
I suggest also that you try your code again but adding before the following

```
    pljson_parser.json_strict := True;
```

which may double your speed depending on the content and structure of your data
and again report here

please reply as soon as possible to this and the previous comment

**Comment by pcrex** [comment] 2017-10-26 09:12
Hi,
I send You e-mail with jsno file.
Benchmark results:
canada.json 13,656 sec 2251051 char
citm_catalog.json 39,844 sec 1727030 char
It took about 48 min. at all.

**Comment by pcrex** [comment] 2017-10-26 09:28
If I run my code with:
`pljson_parser.json_strict := True;`,
I get error:
_ORA-20100: JSON Scanner exception - Unexpected char: T_

**Comment by dsnz** [comment] 2017-10-26 09:36
Hi, thanks

are you sure about 48 min ???
this is outrageous and probably you have very very slow server
in this case the benchmark output is wrong because the code I gave you works only for under 1 min elapsed time
please use the following code (which has some extra additions as I am working on development)

```
declare
  test_sec number;
  
  t_start timestamp;
  t_stop  timestamp;
  t_sec NUMBER;
  
  function time_diff(a timestamp, b timestamp) return number is 
  begin
    return extract (day    from (a-b))*24*60*60 +
           extract (hour   from (a-b))*60*60+
           extract (minute from (a-b))*60+
           extract (second from (a-b));
  end;
  
  procedure bench1(test_dir varchar2, test_file varchar2, test_sec out number) is
    test_json pljson;
    test_clob clob;
    test_bfile bfile;
    
    t_start timestamp;
    t_stop  timestamp;
    t_sec NUMBER;
    
    dest_offset number := 1;
    src_offset number := 1;
    bfile_csid number := 873; -- nls_charset_id(''AL32UTF8');
    lang_context number := dbms_lob.default_lang_ctx;
    warning number;
  begin
  
    t_start := SYSTIMESTAMP;
    
    dbms_lob.createtemporary(test_clob, TRUE, dbms_lob.SESSION);
    dbms_lob.trim(test_clob, 0);
    
    test_bfile := BFILENAME(test_dir, test_file);
    dbms_lob.open(test_bfile, DBMS_LOB.LOB_READONLY);
    dbms_lob.loadclobfromfile(test_clob, test_bfile, DBMS_LOB.LOBMAXSIZE, dest_offset, src_offset, bfile_csid, lang_context, warning);
    dbms_lob.close(test_bfile);
    
    t_stop := SYSTIMESTAMP;
    t_sec := time_diff(t_stop, t_start);
    dbms_output.put_line(test_file || ' load ' || to_char(t_sec) || ' sec (' || dbms_lob.getlength(test_clob) || ' char)');
    
    t_start := SYSTIMESTAMP;
    
    test_json := pljson(test_clob);
    
    t_stop := SYSTIMESTAMP;
    t_sec := time_diff(t_stop, t_start);
    test_sec := t_sec;
    
    dbms_output.put_line(test_file || ' parse ' || to_char(t_sec) || ' sec (' || dbms_lob.getlength(test_clob) || ' char)');
    dbms_lob.freetemporary(test_clob);
  end;
begin
  t_start := SYSTIMESTAMP;
  
  bench1('DATA_PUMP_DIR', 'canada.json', test_sec);
  bench1('DATA_PUMP_DIR', 'citm_catalog.json', test_sec);
  
  t_stop := SYSTIMESTAMP;
  t_sec := time_diff(t_stop, t_start);
  test_sec := t_sec;
  
  dbms_output.put_line('total elapsed ' || to_char(t_sec));
end;
/
```

**Comment by dsnz** [comment] 2017-10-26 09:46
I run your json document with

```
    pljson_parser.json_strict := True;
    test_json := pljson(test_clob);
```

and I get no error and time at 2.6 sec down from 3.3 sec on my humble laptop with Oracle 12c

it's no big improvement (about 20%) but is something

I will see what more can be done and report back
please allow me 1-2 weeks

**Comment by pcrex** [comment] 2017-10-26 11:12
tuned code results:
canada.json load ,125 sec (2251051 char)
canada.json parse 2884,969 sec (2251051 char)
citm_catalog.json load ,563 sec (1727030 char)
citm_catalog.json parse 101,062 sec (1727030 char)
total elapsed 2986,797
About 50 min.
It's our development server, so it isn't fast.

**Comment by dsnz** [comment] 2017-10-26 11:42
almost 2900 sec to parse canada.json (consisting mainly of numbers)
is outrageous compared to citm_catalog.json at 100 sec
I will consider this an outlier result and a peculiarity of your development server

the internal change that was planned and will soon be released which uses object inheritance instead of sys.anyadata in internal representation is almost ready but does not speed up parsing (though it speeds up greatly many other operations)
however I am looking at what can be improved in parsing without changing drastically the entire code

**Comment by dsnz** [comment] 2017-10-27 10:20
just an update on the handling of this issue (and #61 too)

I have discovered an Oracle issue that impacts heavily the performance of parsing of big documents (via clob)
it seems to be a bug present on all Oracle versions and is under investigation now by Oracle after I opened a SR for this case

when I have the final news from Oracle I will report here (hopefully with a commit containing a workaround)  and will also open a new technical description issue about the whole thing
(since the removal of anydata speeds up mainly json manipulations and to_char conversion, it is covered mainly by issue #62 which I will update separately and this issue #105 and #61 will be mainly about parsing speed)

**Comment by dsnz** [comment] 2017-11-20 23:47
@pcrex 

Hello,

Can you please tell me the characterset of the database where you run the test code ?

**Comment by pcrex** [comment] 2017-11-21 06:56
Hello,
'NLS_CHARACTERSET' is 'AL32UTF8'.

**Comment by dsnz** [comment] 2017-11-21 17:26
Hi,

thank you

Oracle has informed me that they have verified bug

Bug 27115721 - POOR PERFORMANCE OF SUBSTR WHEN WORKING ON VARCHAR2 COPIED FROM CLOB IN UNICODE 

and the bug title says it all !
when database characterset is any unicode one then substr on a varchar2 copied from a clob has really very poor performance (even 20x slower)
and this is the main reason of the slowness in parsing in your case

unfortunately the feeling is that there will be no woarkaround and rather a patch will be released

I will keep this issue updated as soon as I have more news from Oracle

I have unicode database and this bug affects me too and I can't profile correctly the parsing code for more speed enhancements, so I think that perhaps we may leave this enhancement out now before moving to release 2.0 (we will introduce it within 2.xx later), what do you think @jsumners ?

**Comment by jsumners** [comment] 2017-11-21 17:37
@dsnz I think you have shown that this is not a bug in PL/JSON, and therefore not a blocker for shipping v2.0.0.

**Comment by dsnz** [comment] 2017-11-21 17:40
good, so I will move on with what remains for 2.0

**Comment by shtock** [comment] 2018-05-17 19:34
as I could see from SR result is is fixed in

Product Version | 12.2.0.1
-- | --

so may be it is time to recheck

**Comment by dsnz** [comment] 2018-05-17 19:42
Hi,

where did you see it is fixed ?
Oracle has not informed me about this and I see nothing like this in the bug description
3 weeks ago they told me that the severity level was finally increased and the situation escalated (so presumably it is getting a lot of attention now ..) but they have not told me the result yet
(12.2.0.1 maybe the version they tried the bug and work on it)

**Comment by shtock** [comment] 2018-05-18 05:43
yep, it seems so

**Comment by dsnz** [comment] 2018-05-18 19:37
don't worry, the issue is tracked
unfortunately Oracle is very slow on this
as soon as there is a development I will post

**Comment by doerwalter** [comment] 2018-12-19 11:49
I don't know if this is related to this issue, but it seems that I have similar problems. The following procedure (which parses a JSON value that is 1836 characters long) takes 27 seconds to complete:

```
create or replace procedure pljson_test
as
	v_source clob := '{"type": "binop_and", "children": [{"type": "binop_and", "children": [{"type": "binop_and", "children": [{"type": "cmp_eq", "children": [{"type": "attr", "value": "r", "children": [{"type": "attr", "value": "color_value", "children": [{"type": "attr", "value": "params", "children": [{"type": "field", "value": "app", "start": 0, "stop": 3}], "start": 0, "stop": 10}], "start": 0, "stop": 22}], "start": 0, "stop": 24}, {"type": "const_int", "value": "51", "start": 28, "stop": 32}], "start": 0, "stop": 32}, {"type": "cmp_eq", "children": [{"type": "attr", "value": "b", "children": [{"type": "attr", "value": "color_value", "children": [{"type": "attr", "value": "params", "children": [{"type": "field", "value": "app", "start": 37, "stop": 40}], "start": 37, "stop": 47}], "start": 37, "stop": 59}], "start": 37, "stop": 61}, {"type": "const_int", "value": "102", "start": 65, "stop": 69}], "start": 37, "stop": 69}], "start": 0, "stop": 69}, {"type": "cmp_eq", "children": [{"type": "attr", "value": "b", "children": [{"type": "attr", "value": "color_value", "children": [{"type": "attr", "value": "params", "children": [{"type": "field", "value": "app", "start": 74, "stop": 77}], "start": 74, "stop": 84}], "start": 74, "stop": 96}], "start": 74, "stop": 98}, {"type": "const_int", "value": "153", "start": 102, "stop": 106}], "start": 74, "stop": 106}], "start": 0, "stop": 106}, {"type": "cmp_eq", "children": [{"type": "attr", "value": "a", "children": [{"type": "attr", "value": "color_value", "children": [{"type": "attr", "value": "params", "children": [{"type": "field", "value": "app", "start": 111, "stop": 114}], "start": 111, "stop": 121}], "start": 111, "stop": 133}], "start": 111, "stop": 135}, {"type": "const_int", "value": "204", "start": 139, "stop": 143}], "start": 111, "stop": 143}], "start": 0, "stop": 143}';
	v_json pljson;
begin
	pljson_parser.json_strict := True;
	dbms_profiler.start_profiler('PL/JSON Test');
	v_json := pljson(v_source);
	dbms_profiler.stop_profiler();
	commit;
end;
```

Profiling results look like this:

|    Time in ns |    % | Counts | type name#line                                                                          |
|---------------| -----|--------|-----------------------------------------------------------------------------------------|
|26,845,873,413 | 100% |        | Total                                                                                   |
| 8,148,132,608 |  30% |     27 | package body PLJSON_PARSER#647: obj.json_data := arr;                                   |
| 5,044,349,744 |  18% |     27 | package body PLJSON_PARSER#648: return obj;                                             |
| 4,045,835,330 |  15% |     19 | package body PLJSON_PARSER#529: return ret_list;                                        |
| 3,521,450,755 |  13% |    120 | package body PLJSON_PARSER#568: return mem;                                             |
| 2,027,624,139 |   7% |     19 | package body PLJSON_PARSER#528: ret_list.list_data := e_arr;                            |
| 1,128,985,334 |   4% |     45 | type body PLJSON_VALUE#13: return;                                                      |
|   451,200,806 |   1% |    120 | package body PLJSON_PARSER#626: arr(x) := jmb;                                          |
|   354,547,047 |   1% |      1 | type body PLJSON#22: return;                                                            |
|   351,465,708 |   1% |      1 | package body PLJSON_PARSER#738: obj := parseObj(tokens, indx);                          |
|   349,850,941 |   1% |      1 | package body PLJSON_PARSER#746: return obj;                                             |
|   303,805,626 |   1% |    120 | package body PLJSON_PARSER#624: jmb := parseMem(tokens, indx, mem_name, x);             |
|   292,180,519 |   1% |     45 | type body PLJSON_VALUE#10: self.object_or_array := elem;                                |
|   153,473,227 |   0% |     19 | package body PLJSON_PARSER#555: e_list := parseArr(tokens, indx);                       |
|   149,908,058 |   0% |     19 | package body PLJSON_PARSER#556: mem := e_list.to_json_value;                            |
|   143,898,694 |   0% |     26 | package body PLJSON_PARSER#509: e_arr(v_count) := parseObj(tokens, indx).to_json_value; |
|   129,443,285 |   0% |     27 | package body PLJSON_PARSER#658: end;                                                    |
|    79,342,558 |   0% |      1 | package body PLJSON_PARSER#747: end parser;                                             |
|    65,219,556 |   0% |    120 | package body PLJSON_PARSER#569: end parseMem;                                           |
|    45,998,621 |   0% |     19 | package body PLJSON_PARSER#530: end parseArr;                                           |
|    15,628,082 |   0% |     19 | type body PLJSON_LIST#340: end;                                                         |
|    13,958,904 |   0% |     26 | type body PLJSON#343: end;                                                              |
|    11,552,628 |   0% |  1,997 | package body PLJSON_PARSER#56: return substr(s.src, indx-s.offset, 1);                  |
|     2,316,013 |   0% |    120 | package body PLJSON_PARSER#532: function parseMem(tokens lTokens, indx in out pls_integer, mem_name varchar2, mem_indx number) return pljson_value as                                                            

(The rest of the profiling entries are below 1ms.)

Database version and encoding:

```
select * from database_properties where property_name in ('NLS_RDBMS_VERSION', 'NLS_CHARACTERSET');
```

| PROPERTY_NAME     |PROPERTY_VALUE |
|-------------------|---------------|
| NLS_RDBMS_VERSION |12.2.0.1.0     |
| NLS_CHARACTERSET  |AL32UTF8       |

**Comment by dsnz** [comment] 2018-12-19 12:48
hello,

I can say I'm sure it is because of the

Bug 27115721 - POOR PERFORMANCE OF SUBSTR WHEN WORKING ON VARCHAR2 COPIED FROM CLOB IN UNICODE

which can slow parsing by 10-20x

however 27 seconds for 1836 characters long is extreme !
I think you get 27 sec with profiling which greatly impacts final performance
profiling should be used only to detect the cause of the problem (as a percent of runtime)
and not as a benchmark indication
so please run again without profiling and also say on which platform/processor do you get this ?

also, the profiling info seems to not really reveal what's happening (it happens often ... with many profilers and options)
can you please write how you did the profiling and how you got this output (commands and options you used) ?

**Comment by doerwalter** [comment] 2018-12-19 13:58
If I comment out the lines`dbms_profiler.start_profiler('PL/JSON Test');` and `dbms_profiler.stop_profiler()`; the command `exec pljson_test;` still takes 27 seconds.

According to our admin the platform is "Red Hat Enterprise Linux Server release 7.5 (Maipo) AMD64" and processors are 8x "Intel(R) Xeon(R) L5640  @ 2.27GHz" (4522.15 Bogomips). The database runs in a docker container.

I'm using the `dbms_profiler` package (the tables and the procedures for this can be found in the files `proftab.sql` and `profload.sql` in the `rdbms/admin` directory of the database installation). The profiling info is basically the output of the following query:

```
	select
		u.unit_type,
		u.unit_owner,
		u.unit_name,
		d.line# as lineno,
		d.total_time,
		d.total_occur,
		s.text
	from
		plsql_profiler_data d,
		plsql_profiler_units u,
		all_source s
	where
		d.runid=(select max(runid) as runid from plsql_profiler_runs) and
		d.total_occur > 0 and
		d.runid = u.runid and
		d.unit_number = u.unit_number and
		u.unit_owner = s.owner and
		u.unit_type = s.type and
		u.unit_name = s.name and
		d.line# = s.line
	order by
		total_time desc
```

**Comment by dsnz** [comment] 2018-12-19 14:22
Hi,

on my low-end development laptop (3+ years old i3 with Windows 10 Home edition, AL32UTF8 12.1 db)
the exact same code you posted (without profiling) takes 5.5 sec !

your server setup seems impressive so I guess it's something with db or Linux setup or the Docker container (perhaps too limited memory available... but I'm speculating of course as I can never have full grasp of your installation and I'm totally ignorant about docker; also parameter PLSQL_OPTIMIZE_LEVEL should normally be 2)

regarding profiling please use the 'PL/SQL Hierarchical Profiler' or dbms_hprof and the plshprof command line utility (though this is not the subject of this issue and will not affect your performance)

**Comment by dsnz** [comment] 2020-05-31 12:45
UPDATE:

there has been no update for 2+ years to pinpoint exactly the cause of this issue which is for a very old and legacy release and furthermore the newest version 3.0 has huge speed improvements for **pljson_ext.get_json_value** since release 3.2.0, and so this issue will be closed

**Closed** 2020-05-31 12:46 UTC
Labels: duplicate, enhancement, waiting Oracle-bugfix
